set nocompatible              " be iMproved, required by Vundle
filetype off                  " required by Vundle

" Plugins are managed by Vundle, which install.sh clones into
" ~/.vim/bundle/Vundle.vim. The guard keeps vim quiet on a machine where that
" has not happened yet.
"
" :PluginInstall  install everything listed below
" :PluginUpdate   update installed plugins
" :PluginClean    remove plugins no longer listed
" See :h vundle for more.
if isdirectory(expand('~/.vim/bundle/Vundle.vim'))
	set rtp+=~/.vim/bundle/Vundle.vim
	call vundle#begin()

	Plugin 'VundleVim/Vundle.vim'
	Plugin 'tpope/vim-fugitive'
	Plugin 'altercation/vim-colors-solarized'

	call vundle#end()
endif

filetype plugin indent on

set number
set showmode
set list
set listchars=tab:>-,trail:~
set colorcolumn=80

set tabstop=4
set shiftwidth=4
set softtabstop=4

syntax enable
set background=dark
let g:solarized_termcolors=256
" silent! so a fresh checkout does not error before :PluginInstall has run
silent! colorscheme solarized
